apiVersion: v1
kind: Service
metadata:
  name: db-master
  annotations:
    cloud.google.com/load-balancer-type: 'Internal'
    networking.gke.io/internal-load-balancer-allow-global-access: 'true'
  labels:
    app: db-master
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo
  selector:
    app: db-master
  # loadBalancerIP: 10.148.11.12