apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  template:
    spec:
      containers:
      - name: back-end
        resources:
          requests:
            cpu: 50m
            memory: 1Gi