apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-master
spec:
  template:
    spec:
      containers:
      - name: db-master
        ports:
          - containerPort: 27017
        resources:
          requests:
            cpu: '300m'
            memory: 4Gi
