apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: front-end
  labels:
    app: front-end
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: front-end
